name: build-windows-installer

on:
  workflow_dispatch: {}
  push:
    tags: ['v*']
    paths:
      - 'backend/**'
      - 'electron/**'
      - 'shared/**'
      - 'requirements.txt'
      - 'electron/package.json'
      - 'electron/main.js'
      - 'electron/preload.js'
      - 'electron/renderer/**'
      - 'scripts/**'

permissions:
  contents: write  # required to create releases and upload assets

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build installer
        shell: pwsh
        run: ./scripts/make-installer.ps1 -Clean

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            electron/dist/*.exe
            electron/dist/*.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            electron/dist/*.exe
            electron/dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
